buildscript {
    repositories {
        mavenCentral()
    }
}

apply plugin: "java-library"

sourceCompatibility = 17
targetCompatibility = 17

dependencies {
    compileOnly(enforcedPlatform("io.spinnaker.clouddriver:clouddriver-bom:${clouddriverVersion}"))

    compileOnly(group: 'com.google.guava', name: 'guava')
    compileOnly(group: 'org.springframework.boot', name: 'spring-boot')
    compileOnly(group: 'com.fasterxml.jackson.core', name: 'jackson-annotations')
    compileOnly(group: 'javax.annotation', name: 'javax.annotation-api')
    compileOnly(group: 'org.slf4j', name: 'slf4j-api')
    compileOnly(group: 'commons-io', name: 'commons-io')
    compileOnly(group: 'org.projectlombok', name: 'lombok', version: '1.18.30')

    annotationProcessor(group: 'org.projectlombok', name: 'lombok', version: '1.18.30')
}
